spring.application.name=spring
spring.datasource.url=jdbc:postgresql://<HOST>:5432/resturant_87di
spring.datasource.username=resturant_87di_user
spring.datasource.password=uGSHrFKldS338CcLPt4KkY5IT6ZkaZNB
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect